/*
 * Tabla nombre -> NPCID, GENERADA de src/npc_id.h por src/oi/gen_npc_names.sh.
 * No editar a mano: regenerar al subir de version del motor.
 */
#include "oi_npc_names.h"

#include <cstring>

namespace
{
struct Entry { const char* name; NPCID id; };

const Entry s_names[] = {
    { "fodder_s3", NPCID_FODDER_S3 },
    { "red_fodder", NPCID_RED_FODDER },
    { "red_fly_fodder", NPCID_RED_FLY_FODDER },
    { "grn_turtle_s3", NPCID_GRN_TURTLE_S3 },
    { "grn_shell_s3", NPCID_GRN_SHELL_S3 },
    { "red_turtle_s3", NPCID_RED_TURTLE_S3 },
    { "red_shell_s3", NPCID_RED_SHELL_S3 },
    { "plant_s3", NPCID_PLANT_S3 },
    { "power_s3", NPCID_POWER_S3 },
    { "coin_s3", NPCID_COIN_S3 },
    { "itemgoal", NPCID_ITEMGOAL },
    { "lavabubble", NPCID_LAVABUBBLE },
    { "plr_fireball", NPCID_PLR_FIREBALL },
    { "fire_power_s3", NPCID_FIRE_POWER_S3 },
    { "miniboss", NPCID_MINIBOSS },
    { "goalorb_s3", NPCID_GOALORB_S3 },
    { "bullet", NPCID_BULLET },
    { "big_bullet", NPCID_BIG_BULLET },
    { "blu_guy", NPCID_BLU_GUY },
    { "red_guy", NPCID_RED_GUY },
    { "cannonenemy", NPCID_CANNONENEMY },
    { "cannonitem", NPCID_CANNONITEM },
    { "glass_turtle", NPCID_GLASS_TURTLE },
    { "glass_shell", NPCID_GLASS_SHELL },
    { "jumper_s3", NPCID_JUMPER_S3 },
    { "spring", NPCID_SPRING },
    { "under_fodder", NPCID_UNDER_FODDER },
    { "red_fish_s1", NPCID_RED_FISH_S1 },
    { "heavy_thrower", NPCID_HEAVY_THROWER },
    { "heavy_thrown", NPCID_HEAVY_THROWN },
    { "key", NPCID_KEY },
    { "coin_switch", NPCID_COIN_SWITCH },
    { "coin_s4", NPCID_COIN_S4 },
    { "leaf_power", NPCID_LEAF_POWER },
    { "grn_boot", NPCID_GRN_BOOT },
    { "spiky_s3", NPCID_SPIKY_S3 },
    { "stone_s3", NPCID_STONE_S3 },
    { "ghost_s3", NPCID_GHOST_S3 },
    { "spit_boss", NPCID_SPIT_BOSS },
    { "spit_boss_ball", NPCID_SPIT_BOSS_BALL },
    { "goalorb_s2", NPCID_GOALORB_S2 },
    { "ghost_fast", NPCID_GHOST_FAST },
    { "ghost_s4", NPCID_GHOST_S4 },
    { "big_ghost", NPCID_BIG_GHOST },
    { "slide_block", NPCID_SLIDE_BLOCK },
    { "fall_block_red", NPCID_FALL_BLOCK_RED },
    { "spiky_thrower", NPCID_SPIKY_THROWER },
    { "spiky_ball_s3", NPCID_SPIKY_BALL_S3 },
    { "toothypipe", NPCID_TOOTHYPIPE },
    { "toothy", NPCID_TOOTHY },
    { "bottom_plant", NPCID_BOTTOM_PLANT },
    { "side_plant", NPCID_SIDE_PLANT },
    { "crab", NPCID_CRAB },
    { "fly", NPCID_FLY },
    { "ext_turtle", NPCID_EXT_TURTLE },
    { "vehicle", NPCID_VEHICLE },
    { "conveyor", NPCID_CONVEYOR },
    { "metalbarrel", NPCID_METALBARREL },
    { "yelswitch_fodder", NPCID_YELSWITCH_FODDER },
    { "yel_platform", NPCID_YEL_PLATFORM },
    { "bluswitch_fodder", NPCID_BLUSWITCH_FODDER },
    { "blu_platform", NPCID_BLU_PLATFORM },
    { "grnswitch_fodder", NPCID_GRNSWITCH_FODDER },
    { "grn_platform", NPCID_GRN_PLATFORM },
    { "redswitch_fodder", NPCID_REDSWITCH_FODDER },
    { "red_platform", NPCID_RED_PLATFORM },
    { "hpipe_short", NPCID_HPIPE_SHORT },
    { "hpipe_long", NPCID_HPIPE_LONG },
    { "vpipe_short", NPCID_VPIPE_SHORT },
    { "vpipe_long", NPCID_VPIPE_LONG },
    { "big_fodder", NPCID_BIG_FODDER },
    { "big_turtle", NPCID_BIG_TURTLE },
    { "big_shell", NPCID_BIG_SHELL },
    { "big_plant", NPCID_BIG_PLANT },
    { "civilian_scared", NPCID_CIVILIAN_SCARED },
    { "grn_fly_turtle_s3", NPCID_GRN_FLY_TURTLE_S3 },
    { "jumper_s4", NPCID_JUMPER_S4 },
    { "tank_treads", NPCID_TANK_TREADS },
    { "short_wood", NPCID_SHORT_WOOD },
    { "long_wood", NPCID_LONG_WOOD },
    { "slant_wood_l", NPCID_SLANT_WOOD_L },
    { "slant_wood_r", NPCID_SLANT_WOOD_R },
    { "slant_wood_m", NPCID_SLANT_WOOD_M },
    { "statue_s3", NPCID_STATUE_S3 },
    { "statue_fire", NPCID_STATUE_FIRE },
    { "villain_s3", NPCID_VILLAIN_S3 },
    { "villain_fire", NPCID_VILLAIN_FIRE },
    { "coin_s1", NPCID_COIN_S1 },
    { "fodder_s1", NPCID_FODDER_S1 },
    { "life_s3", NPCID_LIFE_S3 },
    { "item_buried", NPCID_ITEM_BURIED },
    { "veggie_1", NPCID_VEGGIE_1 },
    { "plant_s1", NPCID_PLANT_S1 },
    { "civilian", NPCID_CIVILIAN },
    { "pet_green", NPCID_PET_GREEN },
    { "item_pod", NPCID_ITEM_POD },
    { "star_exit", NPCID_STAR_EXIT },
    { "pet_blue", NPCID_PET_BLUE },
    { "pet_yellow", NPCID_PET_YELLOW },
    { "pet_red", NPCID_PET_RED },
    { "char2", NPCID_CHAR2 },
    { "char5", NPCID_CHAR5 },
    { "red_coin", NPCID_RED_COIN },
    { "platform_s3", NPCID_PLATFORM_S3 },
    { "checker_platform", NPCID_CHECKER_PLATFORM },
    { "platform_s1", NPCID_PLATFORM_S1 },
    { "pink_civilian", NPCID_PINK_CIVILIAN },
    { "pet_fire", NPCID_PET_FIRE },
    { "grn_turtle_s4", NPCID_GRN_TURTLE_S4 },
    { "red_turtle_s4", NPCID_RED_TURTLE_S4 },
    { "blu_turtle_s4", NPCID_BLU_TURTLE_S4 },
    { "yel_turtle_s4", NPCID_YEL_TURTLE_S4 },
    { "grn_shell_s4", NPCID_GRN_SHELL_S4 },
    { "red_shell_s4", NPCID_RED_SHELL_S4 },
    { "blu_shell_s4", NPCID_BLU_SHELL_S4 },
    { "yel_shell_s4", NPCID_YEL_SHELL_S4 },
    { "grn_hit_turtle_s4", NPCID_GRN_HIT_TURTLE_S4 },
    { "red_hit_turtle_s4", NPCID_RED_HIT_TURTLE_S4 },
    { "blu_hit_turtle_s4", NPCID_BLU_HIT_TURTLE_S4 },
    { "yel_hit_turtle_s4", NPCID_YEL_HIT_TURTLE_S4 },
    { "grn_fly_turtle_s4", NPCID_GRN_FLY_TURTLE_S4 },
    { "red_fly_turtle_s4", NPCID_RED_FLY_TURTLE_S4 },
    { "blu_fly_turtle_s4", NPCID_BLU_FLY_TURTLE_S4 },
    { "yel_fly_turtle_s4", NPCID_YEL_FLY_TURTLE_S4 },
    { "knight", NPCID_KNIGHT },
    { "blu_slime", NPCID_BLU_SLIME },
    { "cyan_slime", NPCID_CYAN_SLIME },
    { "red_slime", NPCID_RED_SLIME },
    { "bird", NPCID_BIRD },
    { "red_spit_guy", NPCID_RED_SPIT_GUY },
    { "blu_spit_guy", NPCID_BLU_SPIT_GUY },
    { "gry_spit_guy", NPCID_GRY_SPIT_GUY },
    { "spit_guy_ball", NPCID_SPIT_GUY_BALL },
    { "bomb", NPCID_BOMB },
    { "walk_bomb_s2", NPCID_WALK_BOMB_S2 },
    { "walk_bomb_s3", NPCID_WALK_BOMB_S3 },
    { "lit_bomb_s3", NPCID_LIT_BOMB_S3 },
    { "coin_s2", NPCID_COIN_S2 },
    { "veggie_2", NPCID_VEGGIE_2 },
    { "veggie_3", NPCID_VEGGIE_3 },
    { "veggie_4", NPCID_VEGGIE_4 },
    { "veggie_5", NPCID_VEGGIE_5 },
    { "veggie_6", NPCID_VEGGIE_6 },
    { "veggie_7", NPCID_VEGGIE_7 },
    { "veggie_8", NPCID_VEGGIE_8 },
    { "veggie_9", NPCID_VEGGIE_9 },
    { "veggie_random", NPCID_VEGGIE_RANDOM },
    { "pet_black", NPCID_PET_BLACK },
    { "pet_purple", NPCID_PET_PURPLE },
    { "pet_pink", NPCID_PET_PINK },
    { "sign", NPCID_SIGN },
    { "ring", NPCID_RING },
    { "poison", NPCID_POISON },
    { "carry_block_a", NPCID_CARRY_BLOCK_A },
    { "carry_block_b", NPCID_CARRY_BLOCK_B },
    { "carry_block_c", NPCID_CARRY_BLOCK_C },
    { "carry_block_d", NPCID_CARRY_BLOCK_D },
    { "saturn", NPCID_SATURN },
    { "lift_sand", NPCID_LIFT_SAND },
    { "rocket_wood", NPCID_ROCKET_WOOD },
    { "red_fly_turtle_s3", NPCID_RED_FLY_TURTLE_S3 },
    { "brute", NPCID_BRUTE },
    { "brute_squished", NPCID_BRUTE_SQUISHED },
    { "big_mole", NPCID_BIG_MOLE },
    { "carry_fodder", NPCID_CARRY_FODDER },
    { "hit_carry_fodder", NPCID_HIT_CARRY_FODDER },
    { "fly_carry_fodder", NPCID_FLY_CARRY_FODDER },
    { "bully", NPCID_BULLY },
    { "statue_power", NPCID_STATUE_POWER },
    { "heavy_power", NPCID_HEAVY_POWER },
    { "plr_heavy", NPCID_PLR_HEAVY },
    { "grn_shell_s1", NPCID_GRN_SHELL_S1 },
    { "grn_turtle_s1", NPCID_GRN_TURTLE_S1 },
    { "red_shell_s1", NPCID_RED_SHELL_S1 },
    { "red_turtle_s1", NPCID_RED_TURTLE_S1 },
    { "grn_fly_turtle_s1", NPCID_GRN_FLY_TURTLE_S1 },
    { "red_fly_turtle_s1", NPCID_RED_FLY_TURTLE_S1 },
    { "axe", NPCID_AXE },
    { "saw", NPCID_SAW },
    { "stone_s4", NPCID_STONE_S4 },
    { "statue_s4", NPCID_STATUE_S4 },
    { "fire_power_s1", NPCID_FIRE_POWER_S1 },
    { "fire_power_s4", NPCID_FIRE_POWER_S4 },
    { "power_s1", NPCID_POWER_S1 },
    { "power_s4", NPCID_POWER_S4 },
    { "life_s1", NPCID_LIFE_S1 },
    { "life_s4", NPCID_LIFE_S4 },
    { "3_life", NPCID_3_LIFE },
    { "skeleton", NPCID_SKELETON },
    { "raft", NPCID_RAFT },
    { "red_boot", NPCID_RED_BOOT },
    { "checkpoint", NPCID_CHECKPOINT },
    { "blu_boot", NPCID_BLU_BOOT },
    { "rainbow_shell", NPCID_RAINBOW_SHELL },
    { "flipped_rainbow_shell", NPCID_FLIPPED_RAINBOW_SHELL },
    { "star_collect", NPCID_STAR_COLLECT },
    { "goaltape", NPCID_GOALTAPE },
    { "char3", NPCID_CHAR3 },
    { "lava_monster", NPCID_LAVA_MONSTER },
    { "villain_s1", NPCID_VILLAIN_S1 },
    { "sick_boss", NPCID_SICK_BOSS },
    { "sick_boss_ball", NPCID_SICK_BOSS_BALL },
    { "flier", NPCID_FLIER },
    { "rocket_flier", NPCID_ROCKET_FLIER },
    { "wall_bug", NPCID_WALL_BUG },
    { "wall_spark", NPCID_WALL_SPARK },
    { "wall_turtle", NPCID_WALL_TURTLE },
    { "boss_case", NPCID_BOSS_CASE },
    { "boss_fragile", NPCID_BOSS_FRAGILE },
    { "homing_ball", NPCID_HOMING_BALL },
    { "homing_ball_gen", NPCID_HOMING_BALL_GEN },
    { "fall_block_brown", NPCID_FALL_BLOCK_BROWN },
    { "grn_vine_s3", NPCID_GRN_VINE_S3 },
    { "red_vine_s3", NPCID_RED_VINE_S3 },
    { "grn_vine_s2", NPCID_GRN_VINE_S2 },
    { "yel_vine_s2", NPCID_YEL_VINE_S2 },
    { "blu_vine_s2", NPCID_BLU_VINE_S2 },
    { "grn_vine_base_s2", NPCID_GRN_VINE_BASE_S2 },
    { "yel_vine_base_s2", NPCID_YEL_VINE_BASE_S2 },
    { "blu_vine_base_s2", NPCID_BLU_VINE_BASE_S2 },
    { "ladder", NPCID_LADDER },
    { "grn_vine_s1", NPCID_GRN_VINE_S1 },
    { "grn_vine_top_s1", NPCID_GRN_VINE_TOP_S1 },
    { "grn_vine_s4", NPCID_GRN_VINE_S4 },
    { "red_vine_top_s3", NPCID_RED_VINE_TOP_S3 },
    { "grn_vine_top_s3", NPCID_GRN_VINE_TOP_S3 },
    { "grn_vine_top_s4", NPCID_GRN_VINE_TOP_S4 },
    { "pet_cyan", NPCID_PET_CYAN },
    { "grn_fish_s3", NPCID_GRN_FISH_S3 },
    { "red_fish_s3", NPCID_RED_FISH_S3 },
    { "squid_s3", NPCID_SQUID_S3 },
    { "goggle_fish", NPCID_GOGGLE_FISH },
    { "grn_fish_s1", NPCID_GRN_FISH_S1 },
    { "bone_fish", NPCID_BONE_FISH },
    { "squid_s1", NPCID_SQUID_S1 },
    { "fish_s4", NPCID_FISH_S4 },
    { "ice_block", NPCID_ICE_BLOCK },
    { "time_switch", NPCID_TIME_SWITCH },
    { "tnt", NPCID_TNT },
    { "timer_s2", NPCID_TIMER_S2 },
    { "earthquake_block", NPCID_EARTHQUAKE_BLOCK },
    { "fodder_s5", NPCID_FODDER_S5 },
    { "fly_fodder_s5", NPCID_FLY_FODDER_S5 },
    { "fly_fodder_s3", NPCID_FLY_FODDER_S3 },
    { "fire_plant", NPCID_FIRE_PLANT },
    { "plant_fire", NPCID_PLANT_FIRE },
    { "stacker", NPCID_STACKER },
    { "timer_s3", NPCID_TIMER_S3 },
    { "power_s2", NPCID_POWER_S2 },
    { "power_s5", NPCID_POWER_S5 },
    { "gem_1", NPCID_GEM_1 },
    { "gem_5", NPCID_GEM_5 },
    { "gem_20", NPCID_GEM_20 },
    { "fly_power", NPCID_FLY_POWER },
    { "lock_door", NPCID_LOCK_DOOR },
    { "long_plant_up", NPCID_LONG_PLANT_UP },
    { "long_plant_down", NPCID_LONG_PLANT_DOWN },
    { "coin_5", NPCID_COIN_5 },
    { "fire_disk", NPCID_FIRE_DISK },
    { "fire_chain", NPCID_FIRE_CHAIN },
    { "walk_plant", NPCID_WALK_PLANT },
    { "bomber_boss", NPCID_BOMBER_BOSS },
    { "ice_cube", NPCID_ICE_CUBE },
    { "ice_power_s3", NPCID_ICE_POWER_S3 },
    { "plr_iceball", NPCID_PLR_ICEBALL },
    { "swordbeam", NPCID_SWORDBEAM },
    { "magic_boss", NPCID_MAGIC_BOSS },
    { "magic_boss_shell", NPCID_MAGIC_BOSS_SHELL },
    { "magic_boss_ball", NPCID_MAGIC_BOSS_BALL },
    { "jump_plant", NPCID_JUMP_PLANT },
    { "bat", NPCID_BAT },
    { "vine_bug", NPCID_VINE_BUG },
    { "swap_power", NPCID_SWAP_POWER },
    { "medal", NPCID_MEDAL },
    { "quad_spitter", NPCID_QUAD_SPITTER },
    { "quad_ball", NPCID_QUAD_BALL },
    { "ice_power_s4", NPCID_ICE_POWER_S4 },
    { "fly_block", NPCID_FLY_BLOCK },
    { "fly_cannon", NPCID_FLY_CANNON },
    { "fire_boss", NPCID_FIRE_BOSS },
    { "fire_boss_shell", NPCID_FIRE_BOSS_SHELL },
    { "fire_boss_fire", NPCID_FIRE_BOSS_FIRE },
    { "item_bubble", NPCID_ITEM_BUBBLE },
    { "item_thrower", NPCID_ITEM_THROWER },
    { "spiky_s4", NPCID_SPIKY_S4 },
    { "spiky_ball_s4", NPCID_SPIKY_BALL_S4 },
    { "random_power", NPCID_RANDOM_POWER },
    { "door_maker", NPCID_DOOR_MAKER },
    { "magic_door", NPCID_MAGIC_DOOR },
    { "cockpit", NPCID_COCKPIT },
    { "char3_heavy", NPCID_CHAR3_HEAVY },
    { "char4_heavy", NPCID_CHAR4_HEAVY },
};
} // namespace

NPCID OI_NpcByName(const char* name)
{
    if(!name || !*name)
        return NPCID_NULL;

    for(const Entry& e : s_names)
    {
        if(std::strcmp(e.name, name) == 0)
            return e.id;
    }

    return NPCID_NULL;
}

int OI_NpcCount()
{
    return (int)(sizeof(s_names) / sizeof(s_names[0]));
}

const char* OI_NpcNameAt(int index, int* id_out)
{
    if(index < 0 || index >= OI_NpcCount())
        return nullptr;

    if(id_out)
        *id_out = (int)s_names[index].id;

    return s_names[index].name;
}
